# load-generator-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: yg-hello-world
spec:
  selector:
    matchLabels:
      run: load-generator
  replicas: 4
  template:
    metadata:
      labels:
        run: load-generator
    spec:
      containers:
      - name: load-generator
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do wget -O- http://$YG_HELLO_WORLD_SERVICE_SERVICE_HOST:8080;done"]
      #  args: "-c", "env | grep -i proxy http_proxy=localhost:8080 https_proxy=localhost:8080 no_proxy=localhost;", "while true; do wget -q -O- http://localhost:30000; done"
      #    - [/bin/sh, -c, 'while true; do wget -q -O- http://localhost:30000; done']
      #  args: [/bin/sh, -c, 'while true; do wget -q -O- http://localhost:30000; done']
