apiVersion: apps/v1
kind: Deployment
metadata:
  name: yg-deployment-mod10
  namespace: yg-hello-world
spec:
  selector:
    matchLabels:
      app: yg-module10
  # replicas: 10       # Don't need this anymore as we are using HorizontalPodAutoscaler
  template:
    metadata:
      labels:
        app: yg-module10
    spec:
      imagePullSecrets:
      - name: regsecret
     #  topologySpreadConstraints:
     #  - maxSkew: 5
     #    topologyKey: kubernetes.io/hostname
     #    whenUnsatisfiable: DoNotSchedule
     #    labelSelector:
     #      matchLabels:
     #        app: yg-module10
      containers:
      - name: nexus1  
        image: nexus1:8123/104194/module6-dockerbuildmaven-sonarqube:yg-nexus-v.9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      
      

---
apiVersion: v1
kind: Service
metadata:
  name: yg-hello-world-service
  namespace: yg-hello-world
spec:
  ports:
  - port: 8080
    nodePort: 30000
  selector:
    app: yg-module10
  type: NodePort

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: yg-deployment-mod10-autoscalling
  namespace: yg-hello-world
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: yg-deployment-mod10
  metrics:
  - type: Resource
    resource:
      name: cpu 
      target:
        type: Utilization
        averageUtilization: 50
  - type: Pods
    pods:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
